function normalizeHeader(v){return String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function cleanGSTIN(v){return String(v??'').trim().toUpperCase()}
function first(obj,names,def=''){for(const n of names){const key=Object.keys(obj||{}).find(k=>normalizeHeader(k)===normalizeHeader(n));if(key!==undefined)return obj[key]}return def}
function parsePeriodFromDate(v){const s=String(v??'').trim();let m=s.match(/^(\d{1,2})[-\/]([A-Za-z]{3})[-\/](\d{2,4})$/);if(m){const mon={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12}[m[2].toLowerCase()];if(mon)return `${Number(m[3])<100?2000+Number(m[3]):Number(m[3])}-${String(mon).padStart(2,'0')}`}m=s.match(/^(\d{4})[-\/](\d{1,2})[-\/]/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}`;m=s.match(/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{4})$/);if(m)return `${m[3]}-${String(m[2]).padStart(2,'0')}`;return ''}
function baseRow(o){return {id:createId(),gstin:cleanGSTIN(o.gstin),party:String(o.party??'').trim(),invoice:String(o.invoice??'').trim(),date:String(o.date??'').trim(),period:o.period||parsePeriodFromDate(o.date),taxable:num(o.taxable),igst:num(o.igst),cgst:num(o.cgst),sgst:num(o.sgst),cess:num(o.cess),value:num(o.value),documentType:o.documentType||'B2B',source:o.source||'Imported',status:o.status||'IMPORTED',portalAction:o.portalAction||'',itcAvailable:o.itcAvailable||'',reverseCharge:o.reverseCharge||'',pos:o.pos||'',originalInvoice:o.originalInvoice||'',originalDate:o.originalDate||'',invoiceType:o.invoiceType||''}}
function normalize2BJson(obj){const root=obj?.data||obj,dd=root?.docdata||{},out=[];function add(parent,doc,type){if(!doc)return;const invoice=first(doc,['inum','ntnum','invoiceNo','invoiceNumber','noteNumber']);const date=first(doc,['dt','idt','invoiceDate','noteDate','date']);out.push(baseRow({gstin:parent?.ctin||parent?.gstin,party:parent?.trdnm||parent?.tradeName||parent?.legalName,invoice,date,taxable:first(doc,['txval','taxableValue','taxable'],0),igst:first(doc,['iamt','igst'],0),cgst:first(doc,['camt','cgst'],0),sgst:first(doc,['samt','sgst'],0),cess:first(doc,['csamt','cess'],0),value:first(doc,['val','invoiceValue','noteValue'],0),documentType:type,source:'2B JSON',status:'IMPORTED',reverseCharge:first(doc,['rev','reverseCharge']),pos:first(doc,['pos','placeOfSupply']),itcAvailable:first(doc,['itcavl','itcAvailable']),originalInvoice:first(doc,['oinum','originalInvoiceNumber']),originalDate:first(doc,['oidt','originalInvoiceDate']),invoiceType:first(doc,['inv_typ','invoiceType'])}))}
for(const [key,type] of [['b2b','B2B'],['b2ba','B2BA'],['cdnr','CDNR'],['cdnra','CDNRA']])for(const parent of (Array.isArray(dd[key])?dd[key]:[])){(parent?.inv||[]).forEach(d=>add(parent,d,type));(parent?.nt||[]).forEach(d=>add(parent,d,type))}
return uniqueRows(out)}
function normalizeIMSJson(obj){const d=obj?.imsDetails||obj?.data?.imsDetails||obj?.data||obj,out=[];function add(x,type){if(!x||typeof x!=='object')return;const isNote=/DN|CN/i.test(type);const invoice=x.inum||x.nt_num||x.invoiceNo||x.noteNo;const row=baseRow({gstin:x.stin||x.ctin||x.gstin,party:x.tradenm||x.trdnm||x.legalName,invoice,date:x.idt||x.nt_dt||x.invdt||x.invoiceDate||x.noteDate,taxable:x.txval||x.taxableValue,igst:x.iamt||x.igst,cgst:x.camt||x.cgst,sgst:x.samt||x.sgst,cess:x.csamt||x.cess,value:x.val||x.inval||x.invoiceValue,documentType:type,source:'IMS JSON',status:'PENDING',portalAction:x.action||x.status||'',originalInvoice:x.oinum||x.oinum2||'',originalDate:x.oidt||'',invoiceType:x.typ||x.inv_typ||''});row.note=isNote;out.push(row)}
for(const [k,t] of [['b2b','B2B'],['b2ba','B2BA'],['b2bdn','B2BDN'],['b2bcn','B2BCN'],['b2bdna','B2BDNA'],['b2bcna','B2BCNA']])(Array.isArray(d[k])?d[k]:[]).forEach(x=>add(x,t));return uniqueRows(out)}
function findHeaderRow(matrix,preds){for(let i=0;i<Math.min(matrix.length,30);i++){const row=(matrix[i]||[]).map(normalizeHeader);if(preds.every(p=>row.some(v=>v.includes(p))))return i}return -1}
function parseIMSMatrix(matrix,sheet){const type=/b2ba/i.test(sheet)?'B2BA':/b2bdn/i.test(sheet)?'B2BDN':/b2bcn/i.test(sheet)?'B2BCN':/b2b/i.test(sheet)?'B2B':'';if(!type)return[];const hr=findHeaderRow(matrix,['gstin','invoice']);if(hr<0)return[];const h=matrix[hr].map(normalizeHeader), idx=(terms,fb)=>{for(const t of terms){const i=h.findIndex(v=>v===normalizeHeader(t)||v.includes(normalizeHeader(t)));if(i>=0)return i}return fb};if(type==='B2BA'){const gst=idx(['gstin'],2),party=idx(['tradenm','legalname'],3),invoice=idx(['revisedinvoicenumber','invoicenumber'],4),date=idx(['revisedinvoicedate'],6),value=idx(['revisedinvoicevalue'],7),status=idx(['status'],8),tax=idx(['taxablevalue'],10),ig=idx(['igst'],11),cg=idx(['cgst'],12),sg=idx(['sgst'],13),ce=idx(['cess'],14);return matrix.slice(hr+1).map(r=>baseRow({gstin:r[gst],party:r[party],invoice:r[invoice],date:r[date],value:r[value],taxable:r[tax],igst:r[ig],cgst:r[cg],sgst:r[sg],cess:r[ce],documentType:type,source:'IMS Excel',status:'PENDING',portalAction:r[status]})).filter(r=>r.gstin&&r.invoice)}
const gst=idx(['gstin'],0),party=idx(['tradenm','legalname'],1),invoice=idx(['invoicenumber','debitnotenumber','creditnotenumber','documentnumber'],2),date=idx(['invoicedate','documentdate'],4),value=idx(['invoicevalue','documentvalue'],5),status=idx(['status'],6),tax=idx(['taxablevalue'],8),ig=idx(['igst'],9),cg=idx(['cgst'],10),sg=idx(['sgst'],11),ce=idx(['cess'],12);return matrix.slice(hr+1).map(r=>baseRow({gstin:r[gst],party:r[party],invoice:r[invoice],date:r[date],value:r[value],taxable:r[tax],igst:r[ig],cgst:r[cg],sgst:r[sg],cess:r[ce],documentType:type,source:'IMS Excel',status:'PENDING',portalAction:r[status]})).filter(r=>r.gstin&&r.invoice)}
function parse2BMatrix(matrix,sheet){const type=/b2ba/i.test(sheet)?'B2BA':/cdn/i.test(sheet)?'CDNR':/b2b/i.test(sheet)?'B2B':'';if(!type)return[];const hr=findHeaderRow(matrix,['gstin','invoice']);if(hr<0)return[];const h=matrix[hr].map(normalizeHeader),idx=(terms,fb)=>{for(const t of terms){const i=h.findIndex(v=>v===normalizeHeader(t)||v.includes(normalizeHeader(t)));if(i>=0)return i}return fb};const gst=idx(['gstin'],0),party=idx(['tradenm','legalname'],1),invoice=idx(['invoicenumber','note number','documentnumber'],2),date=idx(['invoicedate','documentdate','notedate'],4),value=idx(['invoicevalue','documentvalue'],5),tax=idx(['taxablevalue'],8),ig=idx(['igst'],9),cg=idx(['cgst'],10),sg=idx(['sgst'],11),ce=idx(['cess'],12);return matrix.slice(hr+1).map(r=>baseRow({gstin:r[gst],party:r[party],invoice:r[invoice],date:r[date],value:r[value],taxable:r[tax],igst:r[ig],cgst:r[cg],sgst:r[sg],cess:r[ce],documentType:type,source:'2B Excel'})).filter(r=>r.gstin&&r.invoice)}
function parseBooksMatrix(matrix){const hr=findHeaderRow(matrix,['date','particulars','gstin']);if(hr<0)return[];const h=(matrix[hr]||[]).map(normalizeHeader),idx=(terms,fb)=>{for(const t of terms){const i=h.findIndex(v=>v===normalizeHeader(t)||v.includes(normalizeHeader(t)));if(i>=0)return i}return fb};const d=idx(['date'],0),party=idx(['particulars'],1),gst=idx(['partygstinuin','gstin'],2),vch=idx(['vchtype'],3),vno=idx(['vchno'],4),docNo=idx(['docno'],5),docDate=idx(['docdate'],6),tax=idx(['taxable','taxableamount'],7),ig=idx(['igst'],8),cg=idx(['cgst'],9),sg=idx(['sgst'],10),ce=idx(['cess'],11);return matrix.slice(hr+1).map(r=>baseRow({gstin:r[gst],party:r[party],invoice:r[docNo]||r[vno],date:r[docDate]||r[d],taxable:r[tax],igst:r[ig],cgst:r[cg],sgst:r[sg],cess:r[ce],value:num(r[tax])+num(r[ig])+num(r[cg])+num(r[sg])+num(r[ce]),documentType:String(r[vch]||'Purchase'),source:'Books Excel',status:'IMPORTED'})).filter(r=>r.gstin&&r.invoice)}
function uniqueRows(rows){const seen=new Set();return rows.filter(r=>{const k=[r.gstin,r.invoice,r.date,r.value,r.taxable,r.documentType].map(x=>String(x||'').trim().toUpperCase()).join('|');if(!k||seen.has(k))return false;seen.add(k);return true})}
async function importInto(type,file){if(!guardWrite())return;setStatus('Reading '+file.name);let rows=[];if(file.name.toLowerCase().endsWith('.json')){const obj=JSON.parse(await file.text());rows=type==='IMS'?normalizeIMSJson(obj):normalize2BJson(obj)}else{if(!window.XLSX)throw new Error('Excel engine not loaded');const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:false});for(const sn of wb.SheetNames){const matrix=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:''});rows.push(...(type==='IMS'?parseIMSMatrix(matrix,sn):type==='Books'?parseBooksMatrix(matrix):parse2BMatrix(matrix,sn)))}rows=uniqueRows(rows)}const cd=activeData();const before=cd.data[type].length;cd.data[type]=uniqueRows([...cd.data[type],...rows]);save();setStatus('Ready');toast(`${rows.length} records read; ${cd.data[type].length-before} new rows added.`);return rows.length}
window.importEngine={importInto,normalizeIMSJson,normalize2BJson}
function pickImport(type){const input=document.createElement('input');input.type='file';input.accept='.json,.xlsx,.xls';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{await importInto(type,f);if(type==='2B'&&window.twoBModule)render2BPage(twoBTab);else if(type==='IMS'&&window.imsModule)renderIMSPage(imsTab);else if(type==='Books'&&window.booksModule)renderBooksPage()}catch(e){console.error(e);alert('Import failed: '+e.message)}};input.click()}
function exportModule(type,prefix){const rows=activeData().data[type]||[];if(!window.XLSX)return alert('Excel engine not loaded.');const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,prefix);XLSX.writeFile(wb,`${prefix}-${current()?.gstin||'data'}.xlsx`)}
function clearModuleData(type){if(!guardWrite())return;if(confirm(`Clear all ${type} records for this company?`)){activeData().data[type]=[];if(type==='IMS')activeData().imsDecisions={};save();if(type==='2B'&&window.twoBModule)render2BPage(twoBTab);if(type==='IMS'&&window.imsModule)renderIMSPage('all');if(type==='Books'&&window.booksModule)renderBooksPage()}}
