window.reportsModule={init(){if(!current()){location.href='company.html';return}pageShell('reports','Reports','Complete GST report centre — generate, preview and export',`<div id="reportsContent"></div>`);renderReportsHome()}}
let reportType='dashboard';
function reportRows(){const r=buildReco();return {two:r.two,books:r.books,matched:r.two.filter(x=>x.matchStatus==='MATCHED'),mismatch:r.two.filter(x=>x.matchStatus!=='MATCHED'&&x.matchStatus!=='NOT IN BOOKS'),notBooks:r.two.filter(x=>x.matchStatus==='NOT IN BOOKS'),not2b:r.books.filter(x=>x.matchStatus==='NOT IN 2B'),allBooks:r.books,ims:activeData().data.IMS} }
function itc(r){return num(r.igst)+num(r.cgst)+num(r.sgst)+num(r.cess)}
function sumRows(rows){return {taxable:rows.reduce((a,r)=>a+num(r.taxable),0),igst:rows.reduce((a,r)=>a+num(r.igst),0),cgst:rows.reduce((a,r)=>a+num(r.cgst),0),sgst:rows.reduce((a,r)=>a+num(r.sgst),0),cess:rows.reduce((a,r)=>a+num(r.cess),0),itc:rows.reduce((a,r)=>a+itc(r),0),value:rows.reduce((a,r)=>a+num(r.value),0)}}
const REPORTS=[['dashboard','Report Dashboard'],['reconciliation','Detailed Reconciliation'],['party','Party / Supplier'],['invoice','Invoice-wise'],['monthly','Month-wise'],['gstin','GSTIN-wise'],['matched','Matched ITC'],['mismatch','Mismatch / Exceptions'],['notbooks','Missing in Books'],['not2b','Missing in 2B'],['itc','ITC Summary'],['ims','IMS Report'],['threeb','3B / ITC Comparison'],['duplicates','Duplicate Check']];
function renderReportsHome(){document.getElementById('reportsContent').innerHTML=moduleHeader('Reports','Complete report centre',`<button class="btn primary" onclick="exportCurrentReport()">Export Excel</button><button class="btn" onclick="printCurrentReport()">Print / Save PDF</button>`)+`<div class="grid report-menu">${REPORTS.map(([k,n])=>`<button class="tile report-tile ${k===reportType?'active':''}" onclick="openReport('${k}')"><b>${esc(n)}</b><p>Generate current-company report</p></button>`).join('')}</div><div id="reportBody"></div>`;openReport(reportType)}
function openReport(type){reportType=type;const b=document.getElementById('reportBody');if(!b)return;document.querySelectorAll('.report-tile').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.report-tile').forEach(x=>{if(x.textContent.includes(REPORTS.find(r=>r[0]===type)?.[1]||''))x.classList.add('active')});const fn=window['renderReport_'+type];b.innerHTML=fn?fn():'<div class="panel"><div class="panel-body">Report unavailable.</div></div>'}
function reportTable(title,cols,rows){return `<div class="panel report-panel"><div class="panel-head">${esc(title)} <span class="panel-meta">${rows.length} records</span></div><div class="panel-body"><div class="toolbar"><input id="reportSearch" class="searchbox" placeholder="Search report..." oninput="filterReportTable()"></div><div class="table-wrap" style="margin-top:10px"><table id="activeReportTable"><thead><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr>${cols.map(c=>`<td>${c[1]==='#'?i+1:esc(r[c[1]]??'')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">No records.</td></tr>`}</tbody></table></div></div></div>`}
function filterReportTable(){const q=(document.getElementById('reportSearch')?.value||'').toLowerCase();document.querySelectorAll('#activeReportTable tbody tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?'':'none')}
function renderReport_dashboard(){const r=reportRows(), s=sumRows(r.two), sm=sumRows(r.matched), m=sumRows(r.mismatch);return `<div class="grid kpi-grid">${kpi('2B Records',r.two.length)}${kpi('Books Records',r.books.length)}${kpi('Matched',r.matched.length)}${kpi('Mismatch',r.mismatch.length)}${kpi('Missing in Books',r.notBooks.length)}${kpi('Missing in 2B',r.not2b.length)}${kpi('2B ITC',money(s.itc))}${kpi('Matched ITC',money(sm.itc))}</div><div class="grid"><div class="panel"><div class="panel-head">ITC Overview</div><div class="panel-body"><table><tbody><tr><td>GSTR-2B ITC</td><td>${money(s.itc)}</td></tr><tr><td>Matched Books ITC</td><td>${money(sm.itc)}</td></tr><tr><td>Unmatched / Exception ITC</td><td>${money(m.itc)}</td></tr><tr><td>ITC Difference</td><td>${money(s.itc-sm.itc)}</td></tr></tbody></table></div></div><div class="panel"><div class="panel-head">Available Reports</div><div class="panel-body"><p>Party, GSTIN, invoice, monthly, mismatch, missing, IMS, 3B and duplicate reports are available from the menu above.</p></div></div></div>`}
function renderReport_reconciliation(){const r=reportRows();return reportTable('Detailed Reconciliation',[['#','#'],['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Taxable','taxable'],['IGST','igst'],['CGST','cgst'],['SGST','sgst'],['Cess','cess'],['Status','matchStatus']],r.two)}
function renderReport_party(){const r=reportRows(),m=new Map();[...r.two,...r.books].forEach(x=>{const k=cleanGSTIN(x.gstin)||x.party||'UNKNOWN';const a=m.get(k)||{gstin:x.gstin,party:x.party,docs2:0,docsB:0,itc2:0,itcB:0};if(r.two.includes(x)){a.docs2++;a.itc2+=itc(x)}else{a.docsB++;a.itcB+=itc(x)}m.set(k,a)});return reportTable('Party / Supplier Report',[['GSTIN','gstin'],['Party','party'],['2B Docs','docs2'],['Books Docs','docsB'],['2B ITC','itc2'],['Books ITC','itcB']],Array.from(m.values()).map(x=>({...x,itc2:money(x.itc2),itcB:money(x.itcB)})))}
function renderReport_invoice(){const r=reportRows();return reportTable('Invoice-wise Report',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Value','value'],['ITC','itc'],['Status','matchStatus']],r.two.map(x=>({...x,value:money(x.value),itc:money(itc(x))})))}
function renderReport_monthly(){const r=reportRows(),m=new Map();[...r.two,...r.books].forEach(x=>{const p=x.period||parsePeriodFromDate(x.date)||'Unknown';const a=m.get(p)||{period:p,docs2:0,docsB:0,itc2:0,itcB:0};if(r.two.includes(x)){a.docs2++;a.itc2+=itc(x)}else{a.docsB++;a.itcB+=itc(x)}m.set(p,a)});return reportTable('Month-wise ITC Report',[['Period','period'],['2B Docs','docs2'],['Books Docs','docsB'],['2B ITC','itc2'],['Books ITC','itcB'],['Difference','diff']],Array.from(m.values()).map(x=>({...x,itc2:money(x.itc2),itcB:money(x.itcB),diff:money(x.itc2-x.itcB)})))}
function renderReport_gstin(){const r=reportRows(),m=new Map();r.two.forEach(x=>{const k=cleanGSTIN(x.gstin)||'UNKNOWN';const a=m.get(k)||{gstin:k,party:x.party,docs:0,itc:0,matched:0,mismatch:0};a.docs++;a.itc+=itc(x);if(x.matchStatus==='MATCHED')a.matched++;else a.mismatch++;m.set(k,a)});return reportTable('GSTIN-wise Reconciliation',[['GSTIN','gstin'],['Party','party'],['2B Docs','docs'],['Matched','matched'],['Exceptions','mismatch'],['2B ITC','itc']],Array.from(m.values()).map(x=>({...x,itc:money(x.itc)})))}
function renderReport_matched(){const r=reportRows();return reportTable('Matched ITC Report',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Taxable','taxable'],['ITC','itc']],r.matched.map(x=>({...x,itc:money(itc(x))})))}
function renderReport_mismatch(){const r=reportRows();return reportTable('Mismatch / Exception Report',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['ITC','itc'],['Status','matchStatus']],r.mismatch.map(x=>({...x,itc:money(itc(x))})))}
function renderReport_notbooks(){const r=reportRows();return reportTable('Missing in Books',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Taxable','taxable'],['ITC','itc']],r.notBooks.map(x=>({...x,itc:money(itc(x))})))}
function renderReport_not2b(){const r=reportRows();return reportTable('Missing in 2B',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Taxable','taxable'],['ITC','itc']],r.not2b.map(x=>({...x,itc:money(itc(x))})))}
function renderReport_itc(){const r=reportRows(),a=sumRows(r.two),b=sumRows(r.matched),n=sumRows(r.notBooks);return `<div class="panel"><div class="panel-head">ITC Summary</div><div class="panel-body"><table><thead><tr><th>Particular</th><th>Taxable</th><th>IGST</th><th>CGST</th><th>SGST</th><th>Cess</th><th>Total ITC</th></tr></thead><tbody>${[['GSTR-2B',a],['Matched Books',b],['Missing in Books',n]].map(x=>`<tr><td>${x[0]}</td><td>${money(x[1].taxable)}</td><td>${money(x[1].igst)}</td><td>${money(x[1].cgst)}</td><td>${money(x[1].sgst)}</td><td>${money(x[1].cess)}</td><td>${money(x[1].itc)}</td></tr>`).join('')}<tr><th>Difference</th><th></th><th></th><th></th><th></th><th></th><th>${money(a.itc-b.itc)}</th></tr></tbody></table></div></div>`}
function renderReport_ims(){const d=reportRows().ims.map(x=>({...x,decision:imsDecision(x),matchStatus:imsMatchStatus(x,activeData().data.Books),itc:money(itc(x))}));return reportTable('IMS Detailed Report',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Type','documentType'],['Date','date'],['ITC','itc'],['Match','matchStatus'],['Decision','decision'],['Portal Action','portalAction']],d)}
function renderReport_threeb(){const r=reportRows(),a=sumRows(r.two),b=sumRows(r.matched),rcm=r.books.filter(x=>/RCM/i.test(x.documentType||'')||/reverse/i.test(x.reverseCharge||'')),rs=sumRows(rcm),net=a.itc-b.itc-rs.itc;return `<div class="panel"><div class="panel-head">GSTR-3B / ITC Comparison Working</div><div class="panel-body"><table><thead><tr><th>Particular</th><th>Taxable</th><th>IGST</th><th>CGST</th><th>SGST</th><th>Cess</th><th>Total ITC</th></tr></thead><tbody><tr><td>GSTR-2B</td><td>${money(a.taxable)}</td><td>${money(a.igst)}</td><td>${money(a.cgst)}</td><td>${money(a.sgst)}</td><td>${money(a.cess)}</td><td>${money(a.itc)}</td></tr><tr><td>Matched Books</td><td>${money(b.taxable)}</td><td>${money(b.igst)}</td><td>${money(b.cgst)}</td><td>${money(b.sgst)}</td><td>${money(b.cess)}</td><td>${money(b.itc)}</td></tr><tr><td>RCM / Reverse Charge Books</td><td>${money(rs.taxable)}</td><td>${money(rs.igst)}</td><td>${money(rs.cgst)}</td><td>${money(rs.sgst)}</td><td>${money(rs.cess)}</td><td>${money(rs.itc)}</td></tr><tr><th>Net Working Difference</th><th colspan="5"></th><th>${money(net)}</th></tr></tbody></table><p class="form-note">This is a reconciliation working, not a statutory return filing calculation. Verify against filed GSTR-3B.</p></div></div>`}
function renderReport_duplicates(){const r=reportRows(),m=new Map();r.two.forEach(x=>{const k=`${cleanGSTIN(x.gstin)}|${String(x.invoice).trim().toUpperCase()}|${x.date}`;const a=m.get(k)||{gstin:x.gstin,party:x.party,invoice:x.invoice,date:x.date,count:0,itc:0};a.count++;a.itc+=itc(x);m.set(k,a)});const d=Array.from(m.values()).filter(x=>x.count>1).map(x=>({...x,itc:money(x.itc)}));return reportTable('Duplicate 2B Documents',[['GSTIN','gstin'],['Party','party'],['Invoice','invoice'],['Date','date'],['Count','count'],['ITC','itc']],d)}
function exportCurrentReport(){if(!window.XLSX)return alert('Excel engine not loaded.');const r=reportRows();let rows=[];if(reportType==='reconciliation')rows=r.two;else if(reportType==='matched')rows=r.matched;else if(reportType==='mismatch')rows=r.mismatch;else if(reportType==='notbooks')rows=r.notBooks;else if(reportType==='not2b')rows=r.not2b;else if(reportType==='ims')rows=r.ims.map(x=>({...x,decision:imsDecision(x),matchStatus:imsMatchStatus(x,r.books)}));else if(reportType==='invoice')rows=r.two;else if(reportType==='party')rows=r.two;else rows=r.two;const out=rows.map(x=>({...x,totalITC:itc(x),softwareDecision:x.decision||'',reconciliationStatus:x.matchStatus||''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(out),'Report');XLSX.writeFile(wb,`GST-RecoPro-${reportType}-${current().gstin||'company'}.xlsx`)}
function printCurrentReport(){const html=document.getElementById('reportBody')?.innerHTML||'';const w=window.open('','_blank');if(!w)return alert('Popup blocked. Allow popups for PDF/Print.');w.document.write(`<html><head><title>GST RecoPro Report</title><style>body{font-family:Arial;padding:24px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:6px;font-size:11px}th{background:#eee}.panel-head{font-size:18px;font-weight:bold;margin:15px 0}</style></head><body><h1>GST RecoPro — ${esc(current()?.name||'Company')}</h1><p>GSTIN: ${esc(current()?.gstin||'')} | Report: ${esc(REPORTS.find(x=>x[0]===reportType)?.[1]||reportType)}</p>${html}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300)}
